config/routes.rb
Rails.application.routes.draw do
  get 'cocktails/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  belongs_to :cocktail
  belongs_to :ingredient
  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  # has_many :cocktails, through: :doses
  has_many :doses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    cocktail = Cocktail.new(cocktail_params)
    cocktail.save
    redirect_to root_path
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
# Doses
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to root_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      render "cocktails/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class=container>
  <h1>Cocktails</h1>
  <ol>
    <% @cocktails.each do |cocktail| %>
      <li><%=link_to cocktail.name, cocktail_path(cocktail) %> |
        <%= link_to 'x', cocktail_path(cocktail), method: :delete,
        data: { confirm: "Are you sure?" } %> </li>
    <% end %>
  </ol>
  <br>
  <%= link_to "Add a new cocktail", new_cocktail_path %>
</div>

app/views/cocktails/new.html.erb
<div class=container>
  <%= simple_form_for [ @cocktail ] do |f| %>
   <%= f.label "Add a new cocktail" %>
   <%= f.input :name %>
   <%= f.submit "Add cocktail" %>
  <% end %>
<br>
  <%= link_to "Back to cocktails", root_path %>
</div>

app/views/cocktails/show.html.erb
<div class=container>
 <h2><%= @cocktail.name %></h2>

  <ol>
     <% @cocktail.doses.each do |dose| %>
     <li>  <%= dose.ingredient.name %> - <%= dose.description %> |
      <%= link_to 'Delete', dose_path(dose), method: :delete,
        data: { confirm: "Are you sure?" } %> <li>
      <% end %>
  </ol>


  <br>
    <%= link_to "Add a new dose", new_cocktail_dose_path(@cocktail.id) %>
  <br>
   <%= link_to "Add a review", cocktail_reviews_path(@cocktail.id) %>
  <br>
    <%= link_to "Back to cocktails", root_path %>
  <br>
    <%= link_to "Add another cocktail", new_cocktail_path %>
</div>

app/views/doses/new.html.erb
<div class=container>
  <%= simple_form_for [ @cocktail, @dose ] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "Add a dose" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [cocktail, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>